---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://openerz.metaodi.ch/api/calendar.json?region={{ region }}&types={{ type }}&area=a
polling_headers: ''
polling_body: ''
id: 224394
custom_fields:
- keyname: region
  field_type: string
  name: Region
  description: Garbage pickup region
- keyname: type
  field_type: string
  name: Type
  description: Type of garbage
name: Garbager
refresh_interval: 1440
